<?php

namespace Database\Seeders;

use App\Models\HsnSacCode;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class HsnSacCodeSeeder extends Seeder
{
    public function run(): void
    {
        // Comprehensive list of commonly used Indian HSN codes
        $codes = [
            // Chapter 1: Live Animals
            ['code' => '0101', 'description' => 'Live horses, asses, mules, hinnies', 'applicable_to' => 'Goods'],
            ['code' => '0102', 'description' => 'Live bovine animals', 'applicable_to' => 'Goods'],
            ['code' => '0103', 'description' => 'Live swine', 'applicable_to' => 'Goods'],
            ['code' => '0104', 'description' => 'Live sheep and goats', 'applicable_to' => 'Goods'],
            
            // Chapter 2: Meat and Edible Meat Offal
            ['code' => '0201', 'description' => 'Beef, fresh or chilled', 'applicable_to' => 'Goods'],
            ['code' => '0202', 'description' => 'Beef, frozen', 'applicable_to' => 'Goods'],
            ['code' => '0203', 'description' => 'Pork, fresh, chilled or frozen', 'applicable_to' => 'Goods'],
            ['code' => '0207', 'description' => 'Poultry meat, fresh, chilled or frozen', 'applicable_to' => 'Goods'],
            
            // Chapter 3: Fish and Crustaceans
            ['code' => '0301', 'description' => 'Live fish', 'applicable_to' => 'Goods'],
            ['code' => '0302', 'description' => 'Fish, fresh or chilled', 'applicable_to' => 'Goods'],
            ['code' => '0303', 'description' => 'Fish, frozen', 'applicable_to' => 'Goods'],
            
            // Chapter 4: Dairy Products
            ['code' => '0401', 'description' => 'Milk, fresh or with additives', 'applicable_to' => 'Goods'],
            ['code' => '0402', 'description' => 'Milk, concentrated or powdered', 'applicable_to' => 'Goods'],
            ['code' => '0403', 'description' => 'Buttermilk, curdled milk, yoghurt', 'applicable_to' => 'Goods'],
            ['code' => '0404', 'description' => 'Whey', 'applicable_to' => 'Goods'],
            ['code' => '0405', 'description' => 'Butter and other fats', 'applicable_to' => 'Goods'],
            ['code' => '0406', 'description' => 'Cheese and curd', 'applicable_to' => 'Goods'],
            
            // Chapter 5: Products of Animal Origin
            ['code' => '0501', 'description' => 'Human hair, unworked', 'applicable_to' => 'Goods'],
            ['code' => '0511', 'description' => 'Animal products (bones, shells, etc.)', 'applicable_to' => 'Goods'],
            
            // Chapter 6: Trees, Plants, Flowers, Seeds
            ['code' => '0601', 'description' => 'Bulbs, tubers, roots', 'applicable_to' => 'Goods'],
            ['code' => '0602', 'description' => 'Other live plants', 'applicable_to' => 'Goods'],
            
            // Chapter 7: Edible Vegetables
            ['code' => '0701', 'description' => 'Potatoes, fresh or chilled', 'applicable_to' => 'Goods'],
            ['code' => '0702', 'description' => 'Tomatoes, fresh or chilled', 'applicable_to' => 'Goods'],
            ['code' => '0703', 'description' => 'Onions, garlic, leeks, fresh or chilled', 'applicable_to' => 'Goods'],
            ['code' => '0704', 'description' => 'Brassicas (cabbage, cauliflower, broccoli)', 'applicable_to' => 'Goods'],
            ['code' => '0705', 'description' => 'Lettuce and chicory', 'applicable_to' => 'Goods'],
            ['code' => '0706', 'description' => 'Carrots, turnips, beets, radishes', 'applicable_to' => 'Goods'],
            ['code' => '0709', 'description' => 'Other edible vegetables', 'applicable_to' => 'Goods'],
            
            // Chapter 8: Edible Fruits
            ['code' => '0801', 'description' => 'Coconuts, Brazil nuts, cashew nuts', 'applicable_to' => 'Goods'],
            ['code' => '0802', 'description' => 'Other nuts, fresh or dried', 'applicable_to' => 'Goods'],
            ['code' => '0803', 'description' => 'Bananas', 'applicable_to' => 'Goods'],
            ['code' => '0804', 'description' => 'Dates, figs, pineapples, avocados', 'applicable_to' => 'Goods'],
            ['code' => '0805', 'description' => 'Citrus fruits, fresh or dried', 'applicable_to' => 'Goods'],
            ['code' => '0806', 'description' => 'Grapes, fresh or dried', 'applicable_to' => 'Goods'],
            ['code' => '0807', 'description' => 'Melons and watermelons', 'applicable_to' => 'Goods'],
            ['code' => '0808', 'description' => 'Apples, pears, quinces', 'applicable_to' => 'Goods'],
            ['code' => '0809', 'description' => 'Apricots, cherries, peaches, etc.', 'applicable_to' => 'Goods'],
            ['code' => '0810', 'description' => 'Other fruits', 'applicable_to' => 'Goods'],
            
            // Chapter 9: Coffee, Tea, Spices
            ['code' => '0901', 'description' => 'Coffee, not roasted or decaffeinated', 'applicable_to' => 'Goods'],
            ['code' => '0902', 'description' => 'Tea', 'applicable_to' => 'Goods'],
            ['code' => '0904', 'description' => 'Pepper, peppercorns', 'applicable_to' => 'Goods'],
            ['code' => '0905', 'description' => 'Vanilla', 'applicable_to' => 'Goods'],
            ['code' => '0906', 'description' => 'Cinnamon, cinnamom buds', 'applicable_to' => 'Goods'],
            ['code' => '0907', 'description' => 'Cloves', 'applicable_to' => 'Goods'],
            ['code' => '0908', 'description' => 'Nutmeg, mace, cardamom', 'applicable_to' => 'Goods'],
            ['code' => '0909', 'description' => 'Seeds of anise, badian, fennel, etc.', 'applicable_to' => 'Goods'],
            ['code' => '0910', 'description' => 'Ginger, saffron, turmeric, thyme', 'applicable_to' => 'Goods'],
            
            // Chapter 10: Cereals
            ['code' => '1001', 'description' => 'Wheat and meslin', 'applicable_to' => 'Goods'],
            ['code' => '1002', 'description' => 'Rye', 'applicable_to' => 'Goods'],
            ['code' => '1003', 'description' => 'Barley', 'applicable_to' => 'Goods'],
            ['code' => '1004', 'description' => 'Oats', 'applicable_to' => 'Goods'],
            ['code' => '1005', 'description' => 'Corn (maize)', 'applicable_to' => 'Goods'],
            ['code' => '1006', 'description' => 'Rice', 'applicable_to' => 'Goods'],
            ['code' => '1007', 'description' => 'Grain sorghum', 'applicable_to' => 'Goods'],
            
            // Chapter 11: Milling Products
            ['code' => '1101', 'description' => 'Wheat or meslin flour', 'applicable_to' => 'Goods'],
            ['code' => '1102', 'description' => 'Cereal flour (not wheat)', 'applicable_to' => 'Goods'],
            ['code' => '1103', 'description' => 'Cereal groats, meal, pellets', 'applicable_to' => 'Goods'],
            ['code' => '1104', 'description' => 'Cereal grains, worked', 'applicable_to' => 'Goods'],
            ['code' => '1105', 'description' => 'Flour, meal, powder of potato', 'applicable_to' => 'Goods'],
            ['code' => '1106', 'description' => 'Flour of leguminous plants', 'applicable_to' => 'Goods'],
            
            // Chapter 12: Oil Seeds and Oleaginous Fruits
            ['code' => '1201', 'description' => 'Soya beans', 'applicable_to' => 'Goods'],
            ['code' => '1202', 'description' => 'Groundnuts', 'applicable_to' => 'Goods'],
            ['code' => '1205', 'description' => 'Rape or colza seeds', 'applicable_to' => 'Goods'],
            ['code' => '1206', 'description' => 'Sunflower seeds', 'applicable_to' => 'Goods'],
            ['code' => '1207', 'description' => 'Other oil seeds and oleaginous fruits', 'applicable_to' => 'Goods'],
            
            // Chapter 15: Animal or Vegetable Fats and Oils
            ['code' => '1501', 'description' => 'Pig fat (lard)', 'applicable_to' => 'Goods'],
            ['code' => '1502', 'description' => 'Fats of bovine animals', 'applicable_to' => 'Goods'],
            ['code' => '1503', 'description' => 'Lard oil, other animal oils', 'applicable_to' => 'Goods'],
            ['code' => '1504', 'description' => 'Fats and oils from fish or aquatic mammals', 'applicable_to' => 'Goods'],
            ['code' => '1505', 'description' => 'Wool grease and fatty substances', 'applicable_to' => 'Goods'],
            ['code' => '1506', 'description' => 'Other animal fats and oils', 'applicable_to' => 'Goods'],
            ['code' => '1507', 'description' => 'Soya bean oil', 'applicable_to' => 'Goods'],
            ['code' => '1508', 'description' => 'Groundnut oil', 'applicable_to' => 'Goods'],
            ['code' => '1509', 'description' => 'Olive oil', 'applicable_to' => 'Goods'],
            ['code' => '1510', 'description' => 'Other oils (palm, coconut, etc.)', 'applicable_to' => 'Goods'],
            ['code' => '1511', 'description' => 'Palm oil and fractions', 'applicable_to' => 'Goods'],
            ['code' => '1512', 'description' => 'Sunflower, safflower, soya, rape seed oil', 'applicable_to' => 'Goods'],
            ['code' => '1513', 'description' => 'Coconut (copra), palm kernel oils', 'applicable_to' => 'Goods'],
            ['code' => '1514', 'description' => 'Rape, colza, mustard oils', 'applicable_to' => 'Goods'],
            ['code' => '1515', 'description' => 'Other fixed plant oils', 'applicable_to' => 'Goods'],
            ['code' => '1516', 'description' => 'Animal and plant fats and oils, partially hydrogenated', 'applicable_to' => 'Goods'],
            ['code' => '1517', 'description' => 'Margarine, vegetable fat blends', 'applicable_to' => 'Goods'],
            
            // Chapter 17: Sugars and Sugar Confectionery
            ['code' => '1701', 'description' => 'Cane or beet sugar, solid form', 'applicable_to' => 'Goods'],
            ['code' => '1702', 'description' => 'Other sugars', 'applicable_to' => 'Goods'],
            ['code' => '1704', 'description' => 'Sugar confectionery without cocoa', 'applicable_to' => 'Goods'],
            ['code' => '1705', 'description' => 'Cocoa-containing chocolate and cocoa preparations', 'applicable_to' => 'Goods'],
            
            // Chapter 18: Cocoa and Cocoa Preparations
            ['code' => '1801', 'description' => 'Cocoa beans, whole or broken', 'applicable_to' => 'Goods'],
            ['code' => '1802', 'description' => 'Cocoa shells, husks, skins, waste', 'applicable_to' => 'Goods'],
            ['code' => '1803', 'description' => 'Cocoa paste (defatted or not)', 'applicable_to' => 'Goods'],
            ['code' => '1804', 'description' => 'Cocoa butter, fat, oil', 'applicable_to' => 'Goods'],
            ['code' => '1805', 'description' => 'Cocoa powder (unsweetened)', 'applicable_to' => 'Goods'],
            ['code' => '1806', 'description' => 'Chocolate and other cocoa preparations', 'applicable_to' => 'Goods'],
            
            // Chapter 19: Preparations of Cereals, Flour, Starch
            ['code' => '1901', 'description' => 'Extracts, malt, malt flour', 'applicable_to' => 'Goods'],
            ['code' => '1902', 'description' => 'Pasta (macaroni, noodles, rice noodles)', 'applicable_to' => 'Goods'],
            ['code' => '1904', 'description' => 'Breakfast cereals prepared from grain', 'applicable_to' => 'Goods'],
            ['code' => '1905', 'description' => 'Bread, pastry, cakes, biscuits, cookies', 'applicable_to' => 'Goods'],
            
            // Chapter 20: Preparations of Vegetables, Fruit, Nuts
            ['code' => '2001', 'description' => 'Vegetables, fruit, nuts in vinegar or acetic acid', 'applicable_to' => 'Goods'],
            ['code' => '2002', 'description' => 'Tomatoes, prepared or conserved', 'applicable_to' => 'Goods'],
            ['code' => '2003', 'description' => 'Mushrooms, truffles, prepared or conserved', 'applicable_to' => 'Goods'],
            ['code' => '2004', 'description' => 'Other vegetables, prepared or conserved', 'applicable_to' => 'Goods'],
            ['code' => '2005', 'description' => 'Other vegetables, prepared or conserved (continued)', 'applicable_to' => 'Goods'],
            ['code' => '2007', 'description' => 'Jams, fruit jellies, marmalades, fruit paste', 'applicable_to' => 'Goods'],
            ['code' => '2008', 'description' => 'Fruit, nuts, fruit-peel, preserved by sugar', 'applicable_to' => 'Goods'],
            ['code' => '2009', 'description' => 'Fruit and vegetable juices', 'applicable_to' => 'Goods'],
            
            // Chapter 21: Miscellaneous Edible Preparations
            ['code' => '2101', 'description' => 'Extracts, essences, concentrated juice (spices)', 'applicable_to' => 'Goods'],
            ['code' => '2102', 'description' => 'Yeast, dead, inert preparations', 'applicable_to' => 'Goods'],
            ['code' => '2103', 'description' => 'Sauce and preparations, mixed condiments', 'applicable_to' => 'Goods'],
            ['code' => '2104', 'description' => 'Soup and broth preparations', 'applicable_to' => 'Goods'],
            ['code' => '2105', 'description' => 'Ice-cream and edible ice, not containing cocoa', 'applicable_to' => 'Goods'],
            ['code' => '2106', 'description' => 'Other food preparations', 'applicable_to' => 'Goods'],
            
            // Chapter 22: Beverages and Vinegar
            ['code' => '2201', 'description' => 'Waters including mineral and aerated', 'applicable_to' => 'Goods'],
            ['code' => '2202', 'description' => 'Waters with added sugar, non-alcoholic beverages', 'applicable_to' => 'Goods'],
            ['code' => '2203', 'description' => 'Beer made from malt', 'applicable_to' => 'Goods'],
            ['code' => '2204', 'description' => 'Wine of fresh grapes', 'applicable_to' => 'Goods'],
            ['code' => '2205', 'description' => 'Vermouth and other fortified wines', 'applicable_to' => 'Goods'],
            ['code' => '2208', 'description' => 'Ethyl alcohol undenatured, spirits, liqueurs', 'applicable_to' => 'Goods'],
            ['code' => '2209', 'description' => 'Vinegar and substitutes', 'applicable_to' => 'Goods'],
            
            // Chapter 23: Residues from Food Industries
            ['code' => '2301', 'description' => 'Flours, meal from meat, fish, crustaceans', 'applicable_to' => 'Goods'],
            ['code' => '2302', 'description' => 'Bran, sharps and other residues from grain', 'applicable_to' => 'Goods'],
            ['code' => '2303', 'description' => 'Residues of starch manufacture', 'applicable_to' => 'Goods'],
            ['code' => '2304', 'description' => 'Oil-cake and residues from soya oil extraction', 'applicable_to' => 'Goods'],
            
            // Chapter 25: Salt, Sulfur, Lime and Cement
            ['code' => '2501', 'description' => 'Salt (including sea salt)', 'applicable_to' => 'Goods'],
            ['code' => '2502', 'description' => 'Unroasted pyrites', 'applicable_to' => 'Goods'],
            ['code' => '2504', 'description' => 'Natural graphite', 'applicable_to' => 'Goods'],
            ['code' => '2505', 'description' => 'Natural sands', 'applicable_to' => 'Goods'],
            ['code' => '2506', 'description' => 'Quartz sand', 'applicable_to' => 'Goods'],
            ['code' => '2507', 'description' => 'Kaolin (china clay)', 'applicable_to' => 'Goods'],
            ['code' => '2508', 'description' => 'Other mineral substances', 'applicable_to' => 'Goods'],
            ['code' => '2517', 'description' => 'Pebbles, gravel, broken stone', 'applicable_to' => 'Goods'],
            ['code' => '2519', 'description' => 'Crushed stone for concrete', 'applicable_to' => 'Goods'],
            
            // Chapter 27: Mineral Fuels, Mineral Oils, Bituminous Substances
            ['code' => '2701', 'description' => 'Coal, whether or not pulverized', 'applicable_to' => 'Goods'],
            ['code' => '2702', 'description' => 'Lignite (brown coal)', 'applicable_to' => 'Goods'],
            ['code' => '2704', 'description' => 'Coke and semi-coke', 'applicable_to' => 'Goods'],
            ['code' => '2708', 'description' => 'Tar distilled from coal, coke, peat', 'applicable_to' => 'Goods'],
            ['code' => '2709', 'description' => 'Crude oil', 'applicable_to' => 'Goods'],
            ['code' => '2710', 'description' => 'Petroleum oils and bituminous oils', 'applicable_to' => 'Goods'],
            
            // Chapter 28: Inorganic Chemicals
            ['code' => '2801', 'description' => 'Fluorine, chlorine, bromine, iodine', 'applicable_to' => 'Goods'],
            ['code' => '2802', 'description' => 'Sulfur, sublimed or precipitated', 'applicable_to' => 'Goods'],
            ['code' => '2803', 'description' => 'Carbon (carbon black, diamond)', 'applicable_to' => 'Goods'],
            ['code' => '2804', 'description' => 'Hydrogen, rare gases, other nonmetals', 'applicable_to' => 'Goods'],
            ['code' => '2805', 'description' => 'Alkali metals, alkaline earth metals', 'applicable_to' => 'Goods'],
            ['code' => '2806', 'description' => 'Alkali metals, alkaline earth metal oxides', 'applicable_to' => 'Goods'],
            
            // Chapter 29: Organic Chemicals
            ['code' => '2901', 'description' => 'Acyclic hydrocarbons', 'applicable_to' => 'Goods'],
            ['code' => '2902', 'description' => 'Cyclic hydrocarbons', 'applicable_to' => 'Goods'],
            ['code' => '2903', 'description' => 'Halogenated derivatives of hydrocarbons', 'applicable_to' => 'Goods'],
            ['code' => '2904', 'description' => 'Sulfonated, nitrated, nitrosated derivatives', 'applicable_to' => 'Goods'],
            
            // Chapter 30: Pharmaceutical Products
            ['code' => '3001', 'description' => 'Glands and organs for pharmaceutical use', 'applicable_to' => 'Goods'],
            ['code' => '3002', 'description' => 'Vaccines, toxins, cultures for pharmacy', 'applicable_to' => 'Goods'],
            ['code' => '3003', 'description' => 'Medicaments consisting of mixed ingredients', 'applicable_to' => 'Goods'],
            ['code' => '3004', 'description' => 'Medicaments not mixed ingredients', 'applicable_to' => 'Goods'],
            ['code' => '3005', 'description' => 'Bandages, dressings, plasters, medical supplies', 'applicable_to' => 'Goods'],
            ['code' => '3006', 'description' => 'Pharmaceutical preparations, reagents', 'applicable_to' => 'Goods'],
            
            // Chapter 32: Tanning and Dyeing Products
            ['code' => '3201', 'description' => 'Tanning extracts of vegetable origin', 'applicable_to' => 'Goods'],
            ['code' => '3202', 'description' => 'Synthetic organic tanning substances', 'applicable_to' => 'Goods'],
            ['code' => '3204', 'description' => 'Synthetic organic coloring matter', 'applicable_to' => 'Goods'],
            ['code' => '3206', 'description' => 'Other colorants', 'applicable_to' => 'Goods'],
            ['code' => '3207', 'description' => 'Prepared pigments and preparations', 'applicable_to' => 'Goods'],
            
            // Chapter 33: Essential Oils and Perfumery
            ['code' => '3301', 'description' => 'Essential oils and resinoids', 'applicable_to' => 'Goods'],
            ['code' => '3302', 'description' => 'Mixtures of odoriferous substances', 'applicable_to' => 'Goods'],
            ['code' => '3303', 'description' => 'Perfumes and toilet waters', 'applicable_to' => 'Goods'],
            ['code' => '3304', 'description' => 'Beauty and makeup preparations', 'applicable_to' => 'Goods'],
            ['code' => '3305', 'description' => 'Hair preparations', 'applicable_to' => 'Goods'],
            ['code' => '3306', 'description' => 'Oral or dental hygiene preparations', 'applicable_to' => 'Goods'],
            ['code' => '3307', 'description' => 'Pre-shave, shaving creams, aftershave', 'applicable_to' => 'Goods'],
            
            // Chapter 34: Soap, Organic Surfactants
            ['code' => '3401', 'description' => 'Soap and organic surface-active products', 'applicable_to' => 'Goods'],
            ['code' => '3402', 'description' => 'Organic surface-active agents', 'applicable_to' => 'Goods'],
            ['code' => '3403', 'description' => 'Lubricating preparations', 'applicable_to' => 'Goods'],
            ['code' => '3404', 'description' => 'Artificial wax and preparations', 'applicable_to' => 'Goods'],
            ['code' => '3405', 'description' => 'Polishing preparations', 'applicable_to' => 'Goods'],
            
            // Chapter 35: Albuminoidal Substances, Modified Starch
            ['code' => '3502', 'description' => 'Albumins and albumin preparations', 'applicable_to' => 'Goods'],
            ['code' => '3505', 'description' => 'Dextrin, modified starch and preparations', 'applicable_to' => 'Goods'],
            
            // Chapter 38: Miscellaneous Chemical Products
            ['code' => '3801', 'description' => 'Artificial graphite, colloidal graphite', 'applicable_to' => 'Goods'],
            ['code' => '3802', 'description' => 'Activated charcoal', 'applicable_to' => 'Goods'],
            ['code' => '3803', 'description' => 'Tall oil (wood rosin)', 'applicable_to' => 'Goods'],
            ['code' => '3804', 'description' => 'Residual lye from wood pulp production', 'applicable_to' => 'Goods'],
            ['code' => '3805', 'description' => 'Gum, wood rosin and derivatives', 'applicable_to' => 'Goods'],
            
            // Chapter 39: Plastics and Articles
            ['code' => '3901', 'description' => 'Polyethylene', 'applicable_to' => 'Goods'],
            ['code' => '3902', 'description' => 'Polypropylene', 'applicable_to' => 'Goods'],
            ['code' => '3903', 'description' => 'Polystyrene', 'applicable_to' => 'Goods'],
            ['code' => '3904', 'description' => 'Polyvinyl chloride (PVC)', 'applicable_to' => 'Goods'],
            ['code' => '3905', 'description' => 'Polymers of vinyl acetate', 'applicable_to' => 'Goods'],
            ['code' => '3906', 'description' => 'Acrylic polymers', 'applicable_to' => 'Goods'],
            ['code' => '3907', 'description' => 'Polyacetals, polyesters, polyamides', 'applicable_to' => 'Goods'],
            ['code' => '3908', 'description' => 'Polyamides (nylon)', 'applicable_to' => 'Goods'],
            ['code' => '3909', 'description' => 'Phenolic resins', 'applicable_to' => 'Goods'],
            ['code' => '3910', 'description' => 'Silicones', 'applicable_to' => 'Goods'],
            ['code' => '3911', 'description' => 'Petroleum resins, coumarone resins', 'applicable_to' => 'Goods'],
            ['code' => '3912', 'description' => 'Cellulose and chemical derivatives', 'applicable_to' => 'Goods'],
            ['code' => '3913', 'description' => 'Natural polymers', 'applicable_to' => 'Goods'],
            ['code' => '3914', 'description' => 'Ion-exchangers', 'applicable_to' => 'Goods'],
            ['code' => '3915', 'description' => 'Waste, parings, scrap of plastics', 'applicable_to' => 'Goods'],
            ['code' => '3916', 'description' => 'Monofilament of plastics', 'applicable_to' => 'Goods'],
            ['code' => '3917', 'description' => 'Tubes and pipes of plastics', 'applicable_to' => 'Goods'],
            ['code' => '3918', 'description' => 'Floor coverings of plastics', 'applicable_to' => 'Goods'],
            ['code' => '3919', 'description' => 'Self-adhesive plastic plate or sheet', 'applicable_to' => 'Goods'],
            ['code' => '3920', 'description' => 'Other plate, sheet, film of plastics', 'applicable_to' => 'Goods'],
            ['code' => '3921', 'description' => 'Other plastic articles', 'applicable_to' => 'Goods'],
            
            // Chapter 40: Rubber and Articles
            ['code' => '4001', 'description' => 'Natural rubber, latex, gum', 'applicable_to' => 'Goods'],
            ['code' => '4002', 'description' => 'Synthetic rubber', 'applicable_to' => 'Goods'],
            ['code' => '4003', 'description' => 'Reclaimed rubber', 'applicable_to' => 'Goods'],
            ['code' => '4004', 'description' => 'Waste, scrap, powder of rubber', 'applicable_to' => 'Goods'],
            ['code' => '4005', 'description' => 'Compounded rubber', 'applicable_to' => 'Goods'],
            ['code' => '4010', 'description' => 'Conveyor belts of rubber', 'applicable_to' => 'Goods'],
            ['code' => '4012', 'description' => 'Pneumatic tires of rubber', 'applicable_to' => 'Goods'],
            ['code' => '4013', 'description' => 'Inner tubes of rubber', 'applicable_to' => 'Goods'],
            ['code' => '4016', 'description' => 'Other rubber articles', 'applicable_to' => 'Goods'],
            
            // Chapter 41: Hides, Skins, Leather
            ['code' => '4101', 'description' => 'Raw hides and skins of bovine animals', 'applicable_to' => 'Goods'],
            ['code' => '4102', 'description' => 'Raw sheepskins', 'applicable_to' => 'Goods'],
            ['code' => '4103', 'description' => 'Other raw hides and skins', 'applicable_to' => 'Goods'],
            ['code' => '4104', 'description' => 'Prepared leather of bovine animals', 'applicable_to' => 'Goods'],
            ['code' => '4105', 'description' => 'Prepared sheepskin leather', 'applicable_to' => 'Goods'],
            ['code' => '4106', 'description' => 'Other prepared leather', 'applicable_to' => 'Goods'],
            ['code' => '4107', 'description' => 'Leather of bovine animals', 'applicable_to' => 'Goods'],
            ['code' => '4112', 'description' => 'Leather of other animals', 'applicable_to' => 'Goods'],
            ['code' => '4114', 'description' => 'Chamois leather, patent leather', 'applicable_to' => 'Goods'],
            ['code' => '4115', 'description' => 'Composition leather', 'applicable_to' => 'Goods'],
            
            // Chapter 42: Articles of Leather
            ['code' => '4201', 'description' => 'Saddlery and harness articles', 'applicable_to' => 'Goods'],
            ['code' => '4202', 'description' => 'Trunks, briefcases, handbags, wallets', 'applicable_to' => 'Goods'],
            ['code' => '4203', 'description' => 'Gloves and mittens of leather', 'applicable_to' => 'Goods'],
            ['code' => '4205', 'description' => 'Other articles of leather', 'applicable_to' => 'Goods'],
            
            // Chapter 44: Wood and Articles of Wood
            ['code' => '4401', 'description' => 'Fuel wood, in logs, billets, twigs', 'applicable_to' => 'Goods'],
            ['code' => '4402', 'description' => 'Wood charcoal', 'applicable_to' => 'Goods'],
            ['code' => '4403', 'description' => 'Sawlogs and veneer logs', 'applicable_to' => 'Goods'],
            ['code' => '4404', 'description' => 'Hoopwood', 'applicable_to' => 'Goods'],
            ['code' => '4405', 'description' => 'Wood split in the length direction', 'applicable_to' => 'Goods'],
            ['code' => '4406', 'description' => 'Railway sleepers of wood', 'applicable_to' => 'Goods'],
            ['code' => '4407', 'description' => 'Wood sawn lengthwise', 'applicable_to' => 'Goods'],
            ['code' => '4408', 'description' => 'Sheets for veneer, plywood, wallboard', 'applicable_to' => 'Goods'],
            ['code' => '4409', 'description' => 'Wood continuously shaped', 'applicable_to' => 'Goods'],
            ['code' => '4410', 'description' => 'Wood fibreboards and articles', 'applicable_to' => 'Goods'],
            ['code' => '4411', 'description' => 'Particularboard, OSB, similar board', 'applicable_to' => 'Goods'],
            ['code' => '4412', 'description' => 'Plywood, laminboard, laminated wood', 'applicable_to' => 'Goods'],
            ['code' => '4413', 'description' => 'Densified wood and similar combinations', 'applicable_to' => 'Goods'],
            ['code' => '4414', 'description' => 'Wooden frames for paintings, mirrors', 'applicable_to' => 'Goods'],
            ['code' => '4415', 'description' => 'Wooden packing cases, boxes, crates', 'applicable_to' => 'Goods'],
            ['code' => '4416', 'description' => 'Wooden barrels, vats, tubs, cooperage', 'applicable_to' => 'Goods'],
            ['code' => '4417', 'description' => 'Wooden tools, tool handles, broom heads', 'applicable_to' => 'Goods'],
            ['code' => '4418', 'description' => 'Other wooden articles', 'applicable_to' => 'Goods'],
            ['code' => '4419', 'description' => 'Articles of wood, wooden articles nes', 'applicable_to' => 'Goods'],
            
            // Chapter 48: Paper and Paperboard
            ['code' => '4801', 'description' => 'Newsprint in rolls or sheets', 'applicable_to' => 'Goods'],
            ['code' => '4802', 'description' => 'Uncoated paper for printing, writing', 'applicable_to' => 'Goods'],
            ['code' => '4803', 'description' => 'Tissue paper, towels, napkins', 'applicable_to' => 'Goods'],
            ['code' => '4804', 'description' => 'Kraft paper, kraft paperboard', 'applicable_to' => 'Goods'],
            ['code' => '4805', 'description' => 'Other uncoated paper pulp', 'applicable_to' => 'Goods'],
            ['code' => '4806', 'description' => 'Vegetable parchment and greaseproof', 'applicable_to' => 'Goods'],
            ['code' => '4807', 'description' => 'Composite paper (laminated)', 'applicable_to' => 'Goods'],
            ['code' => '4808', 'description' => 'Corrugated paper and paperboard', 'applicable_to' => 'Goods'],
            ['code' => '4809', 'description' => 'Multi-ply paper and paperboard', 'applicable_to' => 'Goods'],
            ['code' => '4810', 'description' => 'Coated paper and paperboard', 'applicable_to' => 'Goods'],
            ['code' => '4811', 'description' => 'Other coated paper and paperboard', 'applicable_to' => 'Goods'],
            ['code' => '4812', 'description' => 'Filter blocks and sheets', 'applicable_to' => 'Goods'],
            ['code' => '4813', 'description' => 'Paper tubes, spools, reels, backs', 'applicable_to' => 'Goods'],
            ['code' => '4814', 'description' => 'Wallpaper and similar coated paper', 'applicable_to' => 'Goods'],
            ['code' => '4815', 'description' => 'Other paper and paperboard', 'applicable_to' => 'Goods'],
            
            // Chapter 49: Printed Books, Periodicals
            ['code' => '4901', 'description' => 'Printed books, brochures, pamphlets', 'applicable_to' => 'Goods'],
            ['code' => '4902', 'description' => 'Newspapers, journals, periodicals', 'applicable_to' => 'Goods'],
            ['code' => '4903', 'description' => 'Children books, picture books', 'applicable_to' => 'Goods'],
            ['code' => '4904', 'description' => 'Music, printed, whether or not bound', 'applicable_to' => 'Goods'],
            ['code' => '4905', 'description' => 'Maps and hydrographic or similar charts', 'applicable_to' => 'Goods'],
            ['code' => '4906', 'description' => 'Plans and drawings for architecturally', 'applicable_to' => 'Goods'],
            ['code' => '4907', 'description' => 'Unused postage, revenue stamps', 'applicable_to' => 'Goods'],
            ['code' => '4908', 'description' => 'Transfers (decalcomanias)', 'applicable_to' => 'Goods'],
            ['code' => '4909', 'description' => 'Printed calendars, postcards, cards', 'applicable_to' => 'Goods'],
            ['code' => '4910', 'description' => 'Printed business forms, labels', 'applicable_to' => 'Goods'],
            ['code' => '4911', 'description' => 'Other printed matter', 'applicable_to' => 'Goods'],
            
            // Chapter 50: Silk and Articles
            ['code' => '5001', 'description' => 'Silk cocoons, suitable for reeling', 'applicable_to' => 'Goods'],
            ['code' => '5002', 'description' => 'Raw silk (not twisted)', 'applicable_to' => 'Goods'],
            ['code' => '5003', 'description' => 'Silk waste', 'applicable_to' => 'Goods'],
            ['code' => '5004', 'description' => 'Silk yarn (not retail packed)', 'applicable_to' => 'Goods'],
            ['code' => '5005', 'description' => 'Silk yarn (retail packed)', 'applicable_to' => 'Goods'],
            ['code' => '5006', 'description' => 'Silk fabric', 'applicable_to' => 'Goods'],
            ['code' => '5007', 'description' => 'Other silk articles', 'applicable_to' => 'Goods'],
            
            // Chapter 51: Wool
            ['code' => '5101', 'description' => 'Wool, not carded or combed', 'applicable_to' => 'Goods'],
            ['code' => '5102', 'description' => 'Fine or coarse animal hair', 'applicable_to' => 'Goods'],
            ['code' => '5103', 'description' => 'Waste of wool or of fine/coarse hair', 'applicable_to' => 'Goods'],
            ['code' => '5104', 'description' => 'Wool or other animal hair, carded', 'applicable_to' => 'Goods'],
            ['code' => '5105', 'description' => 'Yarn of carded wool or animal hair', 'applicable_to' => 'Goods'],
            ['code' => '5106', 'description' => 'Yarn of combed wool or animal hair', 'applicable_to' => 'Goods'],
            ['code' => '5107', 'description' => 'Other yarn of wool or animal hair', 'applicable_to' => 'Goods'],
            ['code' => '5108', 'description' => 'Yarn of carded wool, fine animal hair', 'applicable_to' => 'Goods'],
            ['code' => '5109', 'description' => 'Other yarn of wool or animal hair', 'applicable_to' => 'Goods'],
            ['code' => '5110', 'description' => 'Yarn of coarse animal hair or horsehair', 'applicable_to' => 'Goods'],
            ['code' => '5111', 'description' => 'Woven fabric of wool or animal hair', 'applicable_to' => 'Goods'],
            ['code' => '5112', 'description' => 'Woven fabrics of carded wool or hair', 'applicable_to' => 'Goods'],
            ['code' => '5113', 'description' => 'Other fabric of wool or animal hair', 'applicable_to' => 'Goods'],
            
            // Chapter 52: Cotton
            ['code' => '5201', 'description' => 'Cotton, not carded or combed', 'applicable_to' => 'Goods'],
            ['code' => '5202', 'description' => 'Cotton waste (blending, comber waste)', 'applicable_to' => 'Goods'],
            ['code' => '5203', 'description' => 'Cotton, carded or combed', 'applicable_to' => 'Goods'],
            ['code' => '5204', 'description' => 'Cotton yarn not put up for retail', 'applicable_to' => 'Goods'],
            ['code' => '5205', 'description' => 'Cotton yarn, not retail, single', 'applicable_to' => 'Goods'],
            ['code' => '5206', 'description' => 'Cotton yarn, not retail, multiple', 'applicable_to' => 'Goods'],
            ['code' => '5207', 'description' => 'Cotton yarn put up for retail sale', 'applicable_to' => 'Goods'],
            ['code' => '5208', 'description' => 'Woven fabric of cotton (unbleached)', 'applicable_to' => 'Goods'],
            ['code' => '5209', 'description' => 'Woven cotton fabric, bleached', 'applicable_to' => 'Goods'],
            ['code' => '5210', 'description' => 'Woven cotton fabric, dyed', 'applicable_to' => 'Goods'],
            ['code' => '5211', 'description' => 'Woven cotton fabric, printed', 'applicable_to' => 'Goods'],
            ['code' => '5212', 'description' => 'Other woven cotton fabric', 'applicable_to' => 'Goods'],
            
            // Chapter 54: Synthetic Filaments
            ['code' => '5401', 'description' => 'Synthetic filaments, not put up retail', 'applicable_to' => 'Goods'],
            ['code' => '5402', 'description' => 'Synthetic monofilament yarn', 'applicable_to' => 'Goods'],
            ['code' => '5403', 'description' => 'Synthetic multifilament yarn', 'applicable_to' => 'Goods'],
            ['code' => '5404', 'description' => 'Synthetic filament yarn waste', 'applicable_to' => 'Goods'],
            ['code' => '5405', 'description' => 'Synthetic filament yarn, retail packed', 'applicable_to' => 'Goods'],
            ['code' => '5406', 'description' => 'Man-made filament yarn for non-weaving', 'applicable_to' => 'Goods'],
            ['code' => '5407', 'description' => 'Woven fabric of synthetic filament', 'applicable_to' => 'Goods'],
            ['code' => '5408', 'description' => 'Woven fabric of artificial filament', 'applicable_to' => 'Goods'],
            
            // Chapter 62: Articles of Apparel
            ['code' => '6201', 'description' => 'Mens overcoats, raincoats, jackets', 'applicable_to' => 'Goods'],
            ['code' => '6202', 'description' => 'Womens overcoats, raincoats, jackets', 'applicable_to' => 'Goods'],
            ['code' => '6203', 'description' => 'Mens suits, ensembles, jackets, trousers', 'applicable_to' => 'Goods'],
            ['code' => '6204', 'description' => 'Womens suits, dresses, skirts, trousers', 'applicable_to' => 'Goods'],
            
            // Chapter 64: Footwear
            ['code' => '6401', 'description' => 'Waterproof footwear with outer sole rubber', 'applicable_to' => 'Goods'],
            ['code' => '6402', 'description' => 'Other footwear with outer sole rubber', 'applicable_to' => 'Goods'],
            ['code' => '6403', 'description' => 'Footwear with leather upper sole', 'applicable_to' => 'Goods'],
            ['code' => '6404', 'description' => 'Footwear with upper textile material', 'applicable_to' => 'Goods'],
            ['code' => '6405', 'description' => 'Other footwear', 'applicable_to' => 'Goods'],
            
            // Chapter 70: Glass and Glassware
            ['code' => '7001', 'description' => 'Cullet and other waste glass', 'applicable_to' => 'Goods'],
            ['code' => '7002', 'description' => 'Glass in the mass (not optically worked)', 'applicable_to' => 'Goods'],
            ['code' => '7003', 'description' => 'Cast glass and rolled glass', 'applicable_to' => 'Goods'],
            ['code' => '7004', 'description' => 'Drawn glass and blown glass', 'applicable_to' => 'Goods'],
            ['code' => '7005', 'description' => 'Float glass and surface ground glass', 'applicable_to' => 'Goods'],
            ['code' => '7006', 'description' => 'Glass of subheading 7007', 'applicable_to' => 'Goods'],
            ['code' => '7007', 'description' => 'Tempered (toughened) glass', 'applicable_to' => 'Goods'],
            ['code' => '7008', 'description' => 'Laminated glass', 'applicable_to' => 'Goods'],
            ['code' => '7009', 'description' => 'Glass (not optically worked)', 'applicable_to' => 'Goods'],
            ['code' => '7010', 'description' => 'Carboys, bottles, jars, pots for glass', 'applicable_to' => 'Goods'],
            ['code' => '7011', 'description' => 'Glass envelopes, without fittings', 'applicable_to' => 'Goods'],
            ['code' => '7013', 'description' => 'Other glassware', 'applicable_to' => 'Goods'],
            
            // Chapter 71: Pearls, Precious Stones, Metals
            ['code' => '7101', 'description' => 'Pearls, natural or cultured', 'applicable_to' => 'Goods'],
            ['code' => '7102', 'description' => 'Diamonds whether or not worked', 'applicable_to' => 'Goods'],
            ['code' => '7103', 'description' => 'Precious stones other than diamonds', 'applicable_to' => 'Goods'],
            ['code' => '7108', 'description' => 'Gold including work of gold', 'applicable_to' => 'Goods'],
            ['code' => '7110', 'description' => 'Platinum and work of platinum', 'applicable_to' => 'Goods'],
            
            // Chapter 72: Ferrous Metals
            ['code' => '7201', 'description' => 'Pig iron, spiegeleisen, high-carbon', 'applicable_to' => 'Goods'],
            ['code' => '7202', 'description' => 'Ferroalloys', 'applicable_to' => 'Goods'],
            ['code' => '7203', 'description' => 'Steel in the form of puddled steel', 'applicable_to' => 'Goods'],
            ['code' => '7204', 'description' => 'Waste and scrap of cast iron, steel', 'applicable_to' => 'Goods'],
            ['code' => '7205', 'description' => 'Granulated slag powdered from blast furnace', 'applicable_to' => 'Goods'],
            ['code' => '7206', 'description' => 'Iron and non-alloy steel in ingots', 'applicable_to' => 'Goods'],
            ['code' => '7207', 'description' => 'Semi-finished products of steel', 'applicable_to' => 'Goods'],
            ['code' => '7208', 'description' => 'Flat-rolled products of non-alloy steel', 'applicable_to' => 'Goods'],
            ['code' => '7209', 'description' => 'Flat-rolled products of silicon steel', 'applicable_to' => 'Goods'],
            ['code' => '7210', 'description' => 'Flat-rolled steel coated', 'applicable_to' => 'Goods'],
            ['code' => '7211', 'description' => 'Flat-rolled products steel (other)', 'applicable_to' => 'Goods'],
            ['code' => '7215', 'description' => 'Other bars and rods of steel', 'applicable_to' => 'Goods'],
            ['code' => '7216', 'description' => 'Angles, shapes, sections of steel', 'applicable_to' => 'Goods'],
            ['code' => '7217', 'description' => 'Wire of iron or non-alloy steel', 'applicable_to' => 'Goods'],
            ['code' => '7218', 'description' => 'Stainless steel ingots, semi-finished', 'applicable_to' => 'Goods'],
            ['code' => '7219', 'description' => 'Flat-rolled stainless steel products', 'applicable_to' => 'Goods'],
            ['code' => '7220', 'description' => 'Flat-rolled stainless steel coated', 'applicable_to' => 'Goods'],
            ['code' => '7221', 'description' => 'Bars and rods of stainless steel', 'applicable_to' => 'Goods'],
            ['code' => '7222', 'description' => 'Wire of stainless steel', 'applicable_to' => 'Goods'],
            ['code' => '7225', 'description' => 'Flat-rolled alloy steel', 'applicable_to' => 'Goods'],
            ['code' => '7226', 'description' => 'Other flat-rolled alloy steel', 'applicable_to' => 'Goods'],
            ['code' => '7227', 'description' => 'Bars and rods of alloy steel', 'applicable_to' => 'Goods'],
            ['code' => '7228', 'description' => 'Wire of alloy steel', 'applicable_to' => 'Goods'],
            ['code' => '7301', 'description' => 'Sheet piling of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7302', 'description' => 'Railway or tramway tracks of steel', 'applicable_to' => 'Goods'],
            ['code' => '7304', 'description' => 'Tubes, pipes and blanks of steel', 'applicable_to' => 'Goods'],
            ['code' => '7305', 'description' => 'Other tubes and pipes of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7306', 'description' => 'Other tubes, pipes of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7307', 'description' => 'Tube or pipe fittings of cast iron', 'applicable_to' => 'Goods'],
            ['code' => '7308', 'description' => 'Structures and parts of iron/steel', 'applicable_to' => 'Goods'],
            ['code' => '7309', 'description' => 'Reservoirs, tanks of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7310', 'description' => 'Casks, drums, cans of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7311', 'description' => 'Containers of iron or steel for pressure', 'applicable_to' => 'Goods'],
            ['code' => '7312', 'description' => 'Stranded wire, ropes of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7313', 'description' => 'Barbed wire of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7314', 'description' => 'Cloth, grill, netting of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7315', 'description' => 'Chain and parts of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7316', 'description' => 'Anchors and parts of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7317', 'description' => 'Nails, tacks, screws of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7318', 'description' => 'Other fasteners of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7319', 'description' => 'Sewing needles, bodkins, etc', 'applicable_to' => 'Goods'],
            ['code' => '7320', 'description' => 'Springs of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7321', 'description' => 'Stoves, heating apparatus of iron', 'applicable_to' => 'Goods'],
            ['code' => '7322', 'description' => 'Radiators for central heating of iron', 'applicable_to' => 'Goods'],
            ['code' => '7323', 'description' => 'Other articles of iron or steel', 'applicable_to' => 'Goods'],
            ['code' => '7324', 'description' => 'Sanitary ware and parts of iron/steel', 'applicable_to' => 'Goods'],
            ['code' => '7325', 'description' => 'Cast articles of iron or steel', 'applicable_to' => 'Goods'],
            
            // Chapter 73 continued is shown above, chapter 74: Copper
            ['code' => '7401', 'description' => 'Copper mattes; copper cement, plates', 'applicable_to' => 'Goods'],
            ['code' => '7402', 'description' => 'Unrefined copper, blister copper', 'applicable_to' => 'Goods'],
            ['code' => '7403', 'description' => 'Refined copper and copper alloys', 'applicable_to' => 'Goods'],
            ['code' => '7404', 'description' => 'Copper waste and scrap', 'applicable_to' => 'Goods'],
            ['code' => '7405', 'description' => 'Master alloys of copper', 'applicable_to' => 'Goods'],
            ['code' => '7406', 'description' => 'Copper powders and flakes', 'applicable_to' => 'Goods'],
            ['code' => '7407', 'description' => 'Copper bars, rods and profiles', 'applicable_to' => 'Goods'],
            ['code' => '7408', 'description' => 'Copper wire', 'applicable_to' => 'Goods'],
            ['code' => '7409', 'description' => 'Copper plates, sheets, foil', 'applicable_to' => 'Goods'],
            ['code' => '7410', 'description' => 'Copper foil', 'applicable_to' => 'Goods'],
            ['code' => '7411', 'description' => 'Copper tubes', 'applicable_to' => 'Goods'],
            ['code' => '7412', 'description' => 'Copper tube fittings', 'applicable_to' => 'Goods'],
            ['code' => '7413', 'description' => 'Stranded wire, ropes of copper', 'applicable_to' => 'Goods'],
            ['code' => '7415', 'description' => 'Nails, tacks, screws of copper', 'applicable_to' => 'Goods'],
            ['code' => '7418', 'description' => 'Other articles of copper', 'applicable_to' => 'Goods'],
            
            // Chapter 75: Nickel
            ['code' => '7501', 'description' => 'Nickel mattes, nickel oxide', 'applicable_to' => 'Goods'],
            ['code' => '7502', 'description' => 'Nickel, not alloyed', 'applicable_to' => 'Goods'],
            ['code' => '7503', 'description' => 'Nickel waste and scrap', 'applicable_to' => 'Goods'],
            ['code' => '7504', 'description' => 'Nickel powders and flakes', 'applicable_to' => 'Goods'],
            ['code' => '7505', 'description' => 'Nickel bars, rods, profiles, wire', 'applicable_to' => 'Goods'],
            ['code' => '7506', 'description' => 'Nickel plates, sheets, foil', 'applicable_to' => 'Goods'],
            ['code' => '7507', 'description' => 'Nickel tubes and tube fittings', 'applicable_to' => 'Goods'],
            ['code' => '7508', 'description' => 'Other articles of nickel', 'applicable_to' => 'Goods'],
            
            // Chapter 76: Aluminum
            ['code' => '7601', 'description' => 'Aluminum, not alloyed', 'applicable_to' => 'Goods'],
            ['code' => '7602', 'description' => 'Aluminum alloys', 'applicable_to' => 'Goods'],
            ['code' => '7603', 'description' => 'Aluminum powders, flakes', 'applicable_to' => 'Goods'],
            ['code' => '7604', 'description' => 'Aluminum bars, rods, profiles', 'applicable_to' => 'Goods'],
            ['code' => '7605', 'description' => 'Aluminum wire', 'applicable_to' => 'Goods'],
            ['code' => '7606', 'description' => 'Aluminum plates, sheets, foil', 'applicable_to' => 'Goods'],
            ['code' => '7607', 'description' => 'Aluminum foil', 'applicable_to' => 'Goods'],
            ['code' => '7608', 'description' => 'Aluminum tubes', 'applicable_to' => 'Goods'],
            ['code' => '7609', 'description' => 'Aluminum tube fittings', 'applicable_to' => 'Goods'],
            ['code' => '7610', 'description' => 'Structures and parts of aluminum', 'applicable_to' => 'Goods'],
            ['code' => '7611', 'description' => 'Reservoirs, tanks of aluminum', 'applicable_to' => 'Goods'],
            ['code' => '7612', 'description' => 'Casks, drums, cans of aluminum', 'applicable_to' => 'Goods'],
            ['code' => '7613', 'description' => 'Containers aluminum (pressure vessels)', 'applicable_to' => 'Goods'],
            ['code' => '7614', 'description' => 'Stranded wire, ropes, cable aluminum', 'applicable_to' => 'Goods'],
            ['code' => '7615', 'description' => 'Table, kitchen articles of aluminum', 'applicable_to' => 'Goods'],
            ['code' => '7616', 'description' => 'Other articles of aluminum', 'applicable_to' => 'Goods'],
            
            // Chapter 78: Lead
            ['code' => '7801', 'description' => 'Lead unwrought', 'applicable_to' => 'Goods'],
            ['code' => '7802', 'description' => 'Lead waste, scrap', 'applicable_to' => 'Goods'],
            ['code' => '7804', 'description' => 'Lead plates, sheets, foil', 'applicable_to' => 'Goods'],
            ['code' => '7805', 'description' => 'Lead powders, flakes', 'applicable_to' => 'Goods'],
            ['code' => '7806', 'description' => 'Lead articles', 'applicable_to' => 'Goods'],
            
            // Chapter 79: Zinc
            ['code' => '7901', 'description' => 'Zinc unwrought', 'applicable_to' => 'Goods'],
            ['code' => '7902', 'description' => 'Zinc waste and scrap', 'applicable_to' => 'Goods'],
            ['code' => '7903', 'description' => 'Zinc dust, powders, flakes', 'applicable_to' => 'Goods'],
            ['code' => '7904', 'description' => 'Zinc bars, rods, profiles, wire', 'applicable_to' => 'Goods'],
            ['code' => '7905', 'description' => 'Zinc plates, sheets, foil', 'applicable_to' => 'Goods'],
            ['code' => '7906', 'description' => 'Tubes, tube fittings of zinc', 'applicable_to' => 'Goods'],
            ['code' => '7907', 'description' => 'Other articles of zinc', 'applicable_to' => 'Goods'],
            
            // Chapter 81: Other Base Metals
            ['code' => '8101', 'description' => 'Tungsten (wolfram) and articles', 'applicable_to' => 'Goods'],
            ['code' => '8102', 'description' => 'Molybdenum and articles', 'applicable_to' => 'Goods'],
            ['code' => '8103', 'description' => 'Tantalum and articles', 'applicable_to' => 'Goods'],
            ['code' => '8104', 'description' => 'Magnesium and articles', 'applicable_to' => 'Goods'],
            ['code' => '8105', 'description' => 'Cobalt mattes and other', 'applicable_to' => 'Goods'],
            ['code' => '8106', 'description' => 'Bismuth and articles', 'applicable_to' => 'Goods'],
            ['code' => '8107', 'description' => 'Cadmium and articles', 'applicable_to' => 'Goods'],
            ['code' => '8108', 'description' => 'Titanium and articles', 'applicable_to' => 'Goods'],
            ['code' => '8109', 'description' => 'Zirconium and articles', 'applicable_to' => 'Goods'],
            ['code' => '8110', 'description' => 'Antimony and articles', 'applicable_to' => 'Goods'],
            ['code' => '8111', 'description' => 'Manganese and articles', 'applicable_to' => 'Goods'],
            
            // Chapter 82: Tools, Implements, Cutlery
            ['code' => '8201', 'description' => 'Hand tools, axes, picks', 'applicable_to' => 'Goods'],
            ['code' => '8202', 'description' => 'Saws with metal-bonded teeth', 'applicable_to' => 'Goods'],
            ['code' => '8203', 'description' => 'Files, rasps, chisels', 'applicable_to' => 'Goods'],
            ['code' => '8204', 'description' => 'Hammers, sledgehammers', 'applicable_to' => 'Goods'],
            ['code' => '8205', 'description' => 'Hand tools, wrenches, pliers', 'applicable_to' => 'Goods'],
            ['code' => '8206', 'description' => 'Tools interchangeable with handle', 'applicable_to' => 'Goods'],
            ['code' => '8207', 'description' => 'Interchangeable tools for machinery', 'applicable_to' => 'Goods'],
            ['code' => '8208', 'description' => 'Knives with metal handles', 'applicable_to' => 'Goods'],
            ['code' => '8209', 'description' => 'Knives and blades for machinery', 'applicable_to' => 'Goods'],
            ['code' => '8210', 'description' => 'Butcher and table knives', 'applicable_to' => 'Goods'],
            ['code' => '8211', 'description' => 'Tableware and flatware', 'applicable_to' => 'Goods'],
            ['code' => '8212', 'description' => 'Other cutlery', 'applicable_to' => 'Goods'],
            ['code' => '8213', 'description' => 'Scissors, shears, and blades', 'applicable_to' => 'Goods'],
            ['code' => '8214', 'description' => 'Earpicks, nail files, other small', 'applicable_to' => 'Goods'],
            ['code' => '8215', 'description' => 'Sets of articles', 'applicable_to' => 'Goods'],
            
            // Chapter 84: Machinery
            ['code' => '8401', 'description' => 'Turbines and rotary converters', 'applicable_to' => 'Goods'],
            ['code' => '8402', 'description' => 'Steam generators and superheated water', 'applicable_to' => 'Goods'],
            ['code' => '8403', 'description' => 'Central heating boilers', 'applicable_to' => 'Goods'],
            ['code' => '8404', 'description' => 'Auxiliary plant for steam generators', 'applicable_to' => 'Goods'],
            ['code' => '8405', 'description' => 'Generators of gas with recovery', 'applicable_to' => 'Goods'],
            ['code' => '8406', 'description' => 'Steam turbines', 'applicable_to' => 'Goods'],
            ['code' => '8407', 'description' => 'Spark-ignition reciprocating engines', 'applicable_to' => 'Goods'],
            ['code' => '8408', 'description' => 'Compression-ignition internal engines', 'applicable_to' => 'Goods'],
            ['code' => '8409', 'description' => 'Parts suitable for engines', 'applicable_to' => 'Goods'],
            ['code' => '8410', 'description' => 'Hydraulic turbines, water wheels', 'applicable_to' => 'Goods'],
            ['code' => '8411', 'description' => 'Turbojets, turbopropellers', 'applicable_to' => 'Goods'],
            ['code' => '8412', 'description' => 'Other engines and motors', 'applicable_to' => 'Goods'],
            ['code' => '8413', 'description' => 'Pumps for liquids, liquid elevators', 'applicable_to' => 'Goods'],
            ['code' => '8414', 'description' => 'Air pumps and vacuum pumps', 'applicable_to' => 'Goods'],
            ['code' => '8415', 'description' => 'Air conditioning machines', 'applicable_to' => 'Goods'],
            ['code' => '8416', 'description' => 'Furnace burners', 'applicable_to' => 'Goods'],
            ['code' => '8417', 'description' => 'Industrial furnaces and ovens', 'applicable_to' => 'Goods'],
            ['code' => '8418', 'description' => 'Refrigerating and freezing machinery', 'applicable_to' => 'Goods'],
            ['code' => '8419', 'description' => 'Machinery for heating, cooling', 'applicable_to' => 'Goods'],
            ['code' => '8420', 'description' => 'Calendering and similar rolling', 'applicable_to' => 'Goods'],
            ['code' => '8421', 'description' => 'Centrifuges; filtering apparatus', 'applicable_to' => 'Goods'],
            ['code' => '8422', 'description' => 'Dishwashing machines and machinery', 'applicable_to' => 'Goods'],
            ['code' => '8423', 'description' => 'Weighing machinery', 'applicable_to' => 'Goods'],
            ['code' => '8424', 'description' => 'Spraying machinery, spreading machinery', 'applicable_to' => 'Goods'],
            ['code' => '8425', 'description' => 'Pulley tackle and hoists', 'applicable_to' => 'Goods'],
            ['code' => '8426', 'description' => 'Ships cranes', 'applicable_to' => 'Goods'],
            ['code' => '8427', 'description' => 'Other lifting machinery and apparatus', 'applicable_to' => 'Goods'],
            ['code' => '8428', 'description' => 'Other lifting, loading, unloading', 'applicable_to' => 'Goods'],
            ['code' => '8429', 'description' => 'Self-propelled bulldozers, graders', 'applicable_to' => 'Goods'],
            ['code' => '8430', 'description' => 'Other moving ground excavating', 'applicable_to' => 'Goods'],
            ['code' => '8431', 'description' => 'Parts of excavators, compactors', 'applicable_to' => 'Goods'],
            ['code' => '8432', 'description' => 'Agricultural machinery', 'applicable_to' => 'Goods'],
            ['code' => '8433', 'description' => 'Harvest or threshing machinery', 'applicable_to' => 'Goods'],
            ['code' => '8434', 'description' => 'Milking machines and dairy machinery', 'applicable_to' => 'Goods'],
            ['code' => '8435', 'description' => 'Presses, crushers for agriculture', 'applicable_to' => 'Goods'],
            ['code' => '8436', 'description' => 'Other agricultural machinery', 'applicable_to' => 'Goods'],
            ['code' => '8437', 'description' => 'Machinery for preparing foodstuffs', 'applicable_to' => 'Goods'],
            ['code' => '8438', 'description' => 'Machinery for bread and pastry making', 'applicable_to' => 'Goods'],
            ['code' => '8439', 'description' => 'Machinery for pulp of fibrous material', 'applicable_to' => 'Goods'],
            ['code' => '8440', 'description' => 'Machinery for the working of wood', 'applicable_to' => 'Goods'],
            ['code' => '8441', 'description' => 'Paper making machinery', 'applicable_to' => 'Goods'],
            ['code' => '8442', 'description' => 'Machinery for the printing materials', 'applicable_to' => 'Goods'],
            ['code' => '8443', 'description' => 'Machinery for extruding plastics', 'applicable_to' => 'Goods'],
            ['code' => '8444', 'description' => 'Machinery for working rubber or plastics', 'applicable_to' => 'Goods'],
            ['code' => '8445', 'description' => 'Textile machinery', 'applicable_to' => 'Goods'],
            ['code' => '8446', 'description' => 'Looms for weaving', 'applicable_to' => 'Goods'],
            ['code' => '8447', 'description' => 'Knitting machines', 'applicable_to' => 'Goods'],
            ['code' => '8448', 'description' => 'Machinery for preparing textile fibers', 'applicable_to' => 'Goods'],
            ['code' => '8449', 'description' => 'Machinery for spinning, doubling', 'applicable_to' => 'Goods'],
            ['code' => '8450', 'description' => 'Washing machines for textile fibers', 'applicable_to' => 'Goods'],
            ['code' => '8451', 'description' => 'Machinery for dry cleaning', 'applicable_to' => 'Goods'],
            ['code' => '8452', 'description' => 'Sewing machines', 'applicable_to' => 'Goods'],
            ['code' => '8453', 'description' => 'Machinery for preparing, treating leather', 'applicable_to' => 'Goods'],
            ['code' => '8454', 'description' => 'Machinery for treating metals', 'applicable_to' => 'Goods'],
            ['code' => '8455', 'description' => 'Machine-tools for working metal', 'applicable_to' => 'Goods'],
            ['code' => '8456', 'description' => 'Machine-tools for stone working', 'applicable_to' => 'Goods'],
            ['code' => '8457', 'description' => 'Numeric control machine-tools', 'applicable_to' => 'Goods'],
            ['code' => '8458', 'description' => 'Lathes for removing metal', 'applicable_to' => 'Goods'],
            ['code' => '8459', 'description' => 'Machine-tools for drilling', 'applicable_to' => 'Goods'],
            ['code' => '8460', 'description' => 'Machine-tools for grinding, sharpening', 'applicable_to' => 'Goods'],
            ['code' => '8461', 'description' => 'Machine-tools for sawing, cutting', 'applicable_to' => 'Goods'],
            ['code' => '8462', 'description' => 'Machine-tools for bending, folding', 'applicable_to' => 'Goods'],
            ['code' => '8463', 'description' => 'Other machine-tools', 'applicable_to' => 'Goods'],
            ['code' => '8464', 'description' => 'Water-jet cutting machinery', 'applicable_to' => 'Goods'],
            ['code' => '8465', 'description' => 'Machine-tools for working wood', 'applicable_to' => 'Goods'],
            ['code' => '8466', 'description' => 'Parts and accessories of machine-tools', 'applicable_to' => 'Goods'],
            ['code' => '8467', 'description' => 'Tools for working in hand', 'applicable_to' => 'Goods'],
            ['code' => '8468', 'description' => 'Machinery for welding', 'applicable_to' => 'Goods'],
            ['code' => '8469', 'description' => 'Machinery for soldering, braze', 'applicable_to' => 'Goods'],
            ['code' => '8470', 'description' => 'Calculating machines and cash registers', 'applicable_to' => 'Goods'],
            ['code' => '8471', 'description' => 'Automatic data processing machines', 'applicable_to' => 'Goods'],
            ['code' => '8472', 'description' => 'Other office machines', 'applicable_to' => 'Goods'],
            ['code' => '8473', 'description' => 'Parts and accessories of office machines', 'applicable_to' => 'Goods'],
            ['code' => '8474', 'description' => 'Machinery for sorting, screening', 'applicable_to' => 'Goods'],
            ['code' => '8475', 'description' => 'Machinery for assembling lamps', 'applicable_to' => 'Goods'],
            ['code' => '8476', 'description' => 'Automatic vending machines', 'applicable_to' => 'Goods'],
            ['code' => '8477', 'description' => 'Machinery for working plastic', 'applicable_to' => 'Goods'],
            ['code' => '8478', 'description' => 'Machinery for making paper board', 'applicable_to' => 'Goods'],
            ['code' => '8479', 'description' => 'Machinery and mechanical appliances', 'applicable_to' => 'Goods'],
            ['code' => '8480', 'description' => 'Moulds for metal or metal carbides', 'applicable_to' => 'Goods'],
            ['code' => '8481', 'description' => 'Taps, cocks, valves and similar', 'applicable_to' => 'Goods'],
            ['code' => '8482', 'description' => 'Ball or roller bearings', 'applicable_to' => 'Goods'],
            ['code' => '8483', 'description' => 'Transmission shafts, gearing', 'applicable_to' => 'Goods'],
            ['code' => '8484', 'description' => 'Gaskets and similar seals', 'applicable_to' => 'Goods'],
            ['code' => '8485', 'description' => 'Machinery parts, not elsewhere', 'applicable_to' => 'Goods'],
            
            // Chapter 85: Electrical Machinery, Equipment
            ['code' => '8501', 'description' => 'Electric motors', 'applicable_to' => 'Goods'],
            ['code' => '8502', 'description' => 'Electric generating sets', 'applicable_to' => 'Goods'],
            ['code' => '8503', 'description' => 'Parts suitable for generators', 'applicable_to' => 'Goods'],
            ['code' => '8504', 'description' => 'Electrical transformers', 'applicable_to' => 'Goods'],
            ['code' => '8505', 'description' => 'Electromagnets and permanent magnets', 'applicable_to' => 'Goods'],
            ['code' => '8506', 'description' => 'Primary cells and batteries', 'applicable_to' => 'Goods'],
            ['code' => '8507', 'description' => 'Electric accumulators', 'applicable_to' => 'Goods'],
            ['code' => '8508', 'description' => 'Electromechanical domestic appliances', 'applicable_to' => 'Goods'],
            ['code' => '8509', 'description' => 'Electromechanical appliances', 'applicable_to' => 'Goods'],
            ['code' => '8510', 'description' => 'Shavers and hair clippers, electric', 'applicable_to' => 'Goods'],
            ['code' => '8511', 'description' => 'Electrical ignition systems', 'applicable_to' => 'Goods'],
            ['code' => '8512', 'description' => 'Electrical lighting and signaling', 'applicable_to' => 'Goods'],
            ['code' => '8513', 'description' => 'Portable electric lamps', 'applicable_to' => 'Goods'],
            ['code' => '8514', 'description' => 'Industrial electric furnaces and ovens', 'applicable_to' => 'Goods'],
            ['code' => '8515', 'description' => 'Electric machines and apparatus for welding', 'applicable_to' => 'Goods'],
            ['code' => '8516', 'description' => 'Electric water heaters, immersion', 'applicable_to' => 'Goods'],
            ['code' => '8517', 'description' => 'Telephone sets', 'applicable_to' => 'Goods'],
            ['code' => '8518', 'description' => 'Microphones, loudspeakers', 'applicable_to' => 'Goods'],
            ['code' => '8519', 'description' => 'Turntables, record players', 'applicable_to' => 'Goods'],
            ['code' => '8520', 'description' => 'Magnetic tape, cassette recorders', 'applicable_to' => 'Goods'],
            ['code' => '8521', 'description' => 'Video recording or reproducing', 'applicable_to' => 'Goods'],
            ['code' => '8522', 'description' => 'Magnetic disks, tapes for recording', 'applicable_to' => 'Goods'],
            ['code' => '8523', 'description' => 'Prepared unrecorded media information', 'applicable_to' => 'Goods'],
            ['code' => '8524', 'description' => 'Recorded media information', 'applicable_to' => 'Goods'],
            ['code' => '8525', 'description' => 'Television cameras and recorders', 'applicable_to' => 'Goods'],
            ['code' => '8526', 'description' => 'Radar apparatus, radio navigation', 'applicable_to' => 'Goods'],
            ['code' => '8527', 'description' => 'Radio receivers', 'applicable_to' => 'Goods'],
            ['code' => '8528', 'description' => 'Television receivers', 'applicable_to' => 'Goods'],
            ['code' => '8529', 'description' => 'Parts of reception apparatus', 'applicable_to' => 'Goods'],
            ['code' => '8530', 'description' => 'Electrical signaling apparatus', 'applicable_to' => 'Goods'],
            ['code' => '8531', 'description' => 'Sound or visual signaling apparatus', 'applicable_to' => 'Goods'],
            ['code' => '8532', 'description' => 'Electrical capacitors', 'applicable_to' => 'Goods'],
            ['code' => '8533', 'description' => 'Electrical resistors', 'applicable_to' => 'Goods'],
            ['code' => '8534', 'description' => 'Printed circuits', 'applicable_to' => 'Goods'],
            ['code' => '8535', 'description' => 'Switches and relays', 'applicable_to' => 'Goods'],
            ['code' => '8536', 'description' => 'Apparatus for making or breaking', 'applicable_to' => 'Goods'],
            ['code' => '8537', 'description' => 'Boards, panels for electric control', 'applicable_to' => 'Goods'],
            ['code' => '8538', 'description' => 'Parts of apparatus for making breaking', 'applicable_to' => 'Goods'],
            ['code' => '8539', 'description' => 'Filament lamps', 'applicable_to' => 'Goods'],
            ['code' => '8540', 'description' => 'Thermionic tubes and valves', 'applicable_to' => 'Goods'],
            ['code' => '8541', 'description' => 'Diodes, transistors, FETs', 'applicable_to' => 'Goods'],
            ['code' => '8542', 'description' => 'Electronic integrated circuits', 'applicable_to' => 'Goods'],
            ['code' => '8543', 'description' => 'Electrical machines and apparatus', 'applicable_to' => 'Goods'],
            ['code' => '8544', 'description' => 'Insulated wire, cable and other', 'applicable_to' => 'Goods'],
            ['code' => '8545', 'description' => 'Carbon electrodes, arc lamps', 'applicable_to' => 'Goods'],
            ['code' => '8546', 'description' => 'Electrical insulators of any material', 'applicable_to' => 'Goods'],
            ['code' => '8547', 'description' => 'Insulating fittings', 'applicable_to' => 'Goods'],
            ['code' => '8548', 'description' => 'Waste and scrap of electrical items', 'applicable_to' => 'Goods'],
            
            // Chapter 87: Vehicles
            ['code' => '8701', 'description' => 'Tractors', 'applicable_to' => 'Goods'],
            ['code' => '8702', 'description' => 'Motor vehicles for passenger transport', 'applicable_to' => 'Goods'],
            ['code' => '8703', 'description' => 'Motor cars and other motor vehicles', 'applicable_to' => 'Goods'],
            ['code' => '8704', 'description' => 'Motor vehicles for goods transport', 'applicable_to' => 'Goods'],
            ['code' => '8705', 'description' => 'Special purpose motor vehicles', 'applicable_to' => 'Goods'],
            ['code' => '8706', 'description' => 'Chassis fitted with engines', 'applicable_to' => 'Goods'],
            ['code' => '8707', 'description' => 'Bodies for motor vehicles', 'applicable_to' => 'Goods'],
            ['code' => '8708', 'description' => 'Parts and accessories of motor vehicles', 'applicable_to' => 'Goods'],
            ['code' => '8709', 'description' => 'Works trucks, powered', 'applicable_to' => 'Goods'],
            ['code' => '8710', 'description' => 'Tanks and armored vehicles', 'applicable_to' => 'Goods'],
            ['code' => '8711', 'description' => 'Motorcycles and mopeds', 'applicable_to' => 'Goods'],
            ['code' => '8712', 'description' => 'Bicycles and other cycles', 'applicable_to' => 'Goods'],
            ['code' => '8713', 'description' => 'Carriages and carts', 'applicable_to' => 'Goods'],
            ['code' => '8714', 'description' => 'Parts of bicycles and cycles', 'applicable_to' => 'Goods'],
            ['code' => '8715', 'description' => 'Baby carriages', 'applicable_to' => 'Goods'],
            ['code' => '8716', 'description' => 'Trailers and semi-trailers', 'applicable_to' => 'Goods'],
            
            // Services (SAC codes 9950-9999)
            ['code' => '9950', 'description' => 'Accountancy, book-keeping and audit', 'applicable_to' => 'Service'],
            ['code' => '9951', 'description' => 'Architectural and engineering services', 'applicable_to' => 'Service'],
            ['code' => '9952', 'description' => 'Advertising and business management', 'applicable_to' => 'Service'],
            ['code' => '9953', 'description' => 'Business and management consultancy', 'applicable_to' => 'Service'],
            ['code' => '9954', 'description' => 'Management consultant services', 'applicable_to' => 'Service'],
            ['code' => '9955', 'description' => 'Legal and accounting services', 'applicable_to' => 'Service'],
            ['code' => '9956', 'description' => 'Recruitment and placement services', 'applicable_to' => 'Service'],
            ['code' => '9957', 'description' => 'Technical testing and analysis', 'applicable_to' => 'Service'],
            ['code' => '9958', 'description' => 'Computer and data processing services', 'applicable_to' => 'Service'],
            ['code' => '9959', 'description' => 'Web designing and data entry', 'applicable_to' => 'Service'],
            ['code' => '9960', 'description' => 'Photographic and imaging services', 'applicable_to' => 'Service'],
            ['code' => '9961', 'description' => 'Publishing, printing and related', 'applicable_to' => 'Service'],
            ['code' => '9962', 'description' => 'Courier and transportation services', 'applicable_to' => 'Service'],
            ['code' => '9963', 'description' => 'Postal and telecommunication services', 'applicable_to' => 'Service'],
            ['code' => '9964', 'description' => 'Education and training services', 'applicable_to' => 'Service'],
            ['code' => '9965', 'description' => 'Financial and insurance services', 'applicable_to' => 'Service'],
            ['code' => '9966', 'description' => 'Lodging and accommodation services', 'applicable_to' => 'Service'],
            ['code' => '9967', 'description' => 'Restaurant and catering services', 'applicable_to' => 'Service'],
            ['code' => '9968', 'description' => 'Travel, tourism, entertainment services', 'applicable_to' => 'Service'],
            ['code' => '9969', 'description' => 'Maintenance and repair services', 'applicable_to' => 'Service'],
            ['code' => '9970', 'description' => 'Cleaning and housekeeping services', 'applicable_to' => 'Service'],
            ['code' => '9971', 'description' => 'Pest control and security services', 'applicable_to' => 'Service'],
            ['code' => '9972', 'description' => 'Personal grooming services', 'applicable_to' => 'Service'],
            ['code' => '9973', 'description' => 'Health care services', 'applicable_to' => 'Service'],
            ['code' => '9974', 'description' => 'Sports and other recreation services', 'applicable_to' => 'Service'],
            ['code' => '9975', 'description' => 'Cultural and artistic services', 'applicable_to' => 'Service'],
            ['code' => '9976', 'description' => 'Government and civil services', 'applicable_to' => 'Service'],
            ['code' => '9977', 'description' => 'Rent of property services', 'applicable_to' => 'Service'],
            ['code' => '9978', 'description' => 'R&D and other professional services', 'applicable_to' => 'Service'],
            ['code' => '9979', 'description' => 'Other services', 'applicable_to' => 'Service'],
        ];

        foreach ($codes as $hsn) {
            HsnSacCode::firstOrCreate(
                ['code' => $hsn['code']],
                [
                    'slug' => Str::slug($hsn['code'] . ' ' . $hsn['description']),
                    'description' => $hsn['description'],
                    'applicable_to' => $hsn['applicable_to'],
                ]
            );
        }
    }
}
